using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Configuration;
using WebApplication3.Models;

namespace WebApplication3
{
    public partial class WebForm11 : System.Web.UI.Page
    {
        singletonDbConnection obj = singletonDbConnection.getobj();
        SqlConnection con;
        protected void Page_Load(object sender, EventArgs e)
        {
            // string strcon = ConfigurationManager.ConnectionStrings["db"].ConnectionString;
            // using (SqlConnection con = new SqlConnection(strcon))
            // {
           
                    con = obj.Con;
                SqlCommand com = new SqlCommand("ReturnId", con);
                com.CommandType = CommandType.StoredProcedure;

                com.Parameters.AddWithValue("@Username", Session["username"]);

                SqlParameter outparam = new SqlParameter();
                outparam.ParameterName = "@id";
                outparam.SqlDbType = System.Data.SqlDbType.VarChar;
                outparam.Direction = System.Data.ParameterDirection.Output;
                outparam.Size = 50;
                com.Parameters.Add(outparam);
            try
            {
                if (con.State != ConnectionState.Open) //connection object may have broken, executing, etc states so we should not use state==closed)
                {
                    con.Open();
                }
                com.ExecuteNonQuery();

                String empId = outparam.Value.ToString();
                Label1.Text = empId;

                con.Close();
            }
            catch(Exception er)
            {
                Response.Write(er);
            }
          //  }
        }

        protected void ButtonSubmit_Click(object sender, EventArgs e)
        {
            //string strcon = ConfigurationManager.ConnectionStrings["db"].ConnectionString;
            // using (SqlConnection con = new SqlConnection(strcon))
            // {
            con = obj.Con; 
                SqlCommand cmd = new SqlCommand("SubmitComplaint", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@C_body", TextBox1.Text);
                cmd.Parameters.AddWithValue("@C_DOS", DateTime.Now.ToShortDateString());
                cmd.Parameters.AddWithValue("@C_SB", Label1.Text);
                cmd.Parameters.AddWithValue("@C_type", DropDownList1.SelectedValue);

                SqlParameter outid = new SqlParameter();
                outid.ParameterName = "@Id";
                outid.SqlDbType = System.Data.SqlDbType.Int;
                outid.Direction = System.Data.ParameterDirection.Output;
                outid.Size = 50;
                cmd.Parameters.Add(outid);
            try
            {
                if (con.State != ConnectionState.Open) //connection object may have broken, executing, etc states so we should not use state==closed)
                {
                    con.Open();
                }
                int k = cmd.ExecuteNonQuery();   //no. of rows affected
                int cId = (int)outid.Value;      //compalint_id (autogenerated) returned.

                //only to store in a complaint object-(not needed otherwise)

                complaint comp = new complaint();
                employee emp = new employee();
                emp.EmployeeId = Label1.Text;
                comp.Complaint_body = TextBox1.Text;

                comp.Date_of_submission = DateTime.Today;
                comp.Type = DropDownList1.SelectedValue;
                comp.Submitted_By = emp;
                comp.Status = "Pending";
                comp.ComplaintId = cId;


                if (k != 0)
                {

                    con.Close();
                    ClientScript.RegisterStartupScript(this.GetType(), "alert", "alert('Complaint Registered!! Complaint id is= " + cId.ToString() + " ' );window.location.href='ecPortalM.aspx';", true);

                }


                con.Close();
                //}
            }
            catch(Exception er)
            {
                Response.Write(er);
            }
        

        }


        protected void btnBack_Click(object sender, EventArgs e)
        {
            Response.Redirect("ecPortalM.aspx");
        }
    }
}








